// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rgyvqmpajfbqtynmjcfu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJneXZxbXBhamZicXR5bm1qY2Z1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1MjE1MTMsImV4cCI6MjA2NDA5NzUxM30.1czf9QaH0IlOKV5iBB2GFWwVTC_cPSXb--repTWGZ34";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);